# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: xylang Maven Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build and test project
      run: mvn -B package --file pom.xml
      
    - name: Upload xylang Release
      uses: ncipollo/release-action@v1.8.6
      with:
          artifacts: /home/runner/work/xylangCore/xylangCore/target/xylang*.jar
          name: "xyLang Release"
          tag: "xyLang-ci"
          token: ${{ secrets.GITHUB_TOKEN }}